rem start spinavbatchfilelines.exe 30.0 "random" "guitar"
rem start spinavbatchfilelines.exe 30.0 "random" "kick"
rem start spinavbatchfilelines.exe 30.0 "random" "drum"
rem start spinavbatchfilelines.exe 30.0 "random" "kit"
rem start spinavbatchfilelines.exe 30.0 "random" "synth"
rem start spinavbatchfilelines.exe 30.0 "random" "bass"
rem start spinavbatchfilelines.exe 30.0 "random" "brass"
start spinavbatchfilelines.exe 30.0 "random" "orchestral"
